### ISSUE TITLE
Branch names need adjustment

### ISSUE THREAD

**Issue by austinlucaslake** [SC-Robotics-2023/arm_2022_23#1]
The branch names don't seem to be following any convention. If possible let's try and rename branches to follow a C-style convention for consistency. (i.e. `new_feature`, `end_effector`, `gamepad_interface`, etc.)

**Comment by jasperdoan** [comment]
Will do!

Thanks for the feedback

**Comment by austinlucaslake** [comment]
Keep this open until the changes are made.

**Comment by jasperdoan** [comment]
Just renamed them before I closed it. Could you revise it? 

Thanks.

**Comment by austinlucaslake** [comment]
I review and modified them to simplify the names a bit.
The new branch names are `hall_polarity` and `odrive_config`.
